### ISSUE TITLE
Wrong namespace on creating class

### ISSUE THREAD

**Issue by ErickMBS** [MoaidHathot/dotnet.nvim#1]
Wrong namespace on creating class

![image](https://github.com/MoaidHathot/dotnet.nvim/assets/59985742/f6559f6f-8207-451b-bab2-1e5999b6505a)

![image](https://github.com/MoaidHathot/dotnet.nvim/assets/59985742/d2629f9c-27e8-4e14-a05b-88359b4219a7)

**Comment by MoaidHathot** [comment]
Hi @ErickMBS, thank you for reporting the issue. In order to reproduce and troubleshoot, could you please mention where is your csproj located and what is its name? You don't have to specify the redacted name, use `foo` instead.

**Comment by ErickMBS** [comment]
Possible fix:
[dotnet.nvim.zip](https://github.com/user-attachments/files/15676730/dotnet.nvim.zip)

**Comment by MoaidHathot** [comment]
@ErickMBS, I will take a look, thanks!
If you could create a PR it will be easier, but don't feel pressured to do it :)

**Comment by ErickMBS** [comment]
Thanks @MoaidHathot, I tryed to create a new branch with the changes, but it seems I don't have permissions :/

**Comment by MoaidHathot** [comment]
@ErickMBS, as to be aligned with the Github flow, you should `fork` the repo, do the changes there then create a PR from your fork into this repo :)
