### ISSUE TITLE
Document fd dependency with debian distros for project package adding functionality

### ISSUE THREAD

**Issue by IbraWorks** [MoaidHathot/dotnet.nvim#4]
Thanks for this neat plugin. I'm new to dotnet with nvim and this plugin has helped my workflow. I appreciate all your hard work :pray: 

The `"<cmd>:DotnetUI project package add<CR>"` could not find my projects and so was failing. Upon digging I noticed the fd command [here](https://github.com/MoaidHathot/dotnet.nvim/blob/main/lua/dotnet/ui/windows/window-utils.lua#L22).

I'm using an ubuntu machine, where `fd` is installed as `fdfind`.
I had to create a symlink to get the "fd" name. 
Issue is documented [here](https://github.com/sharkdp/fd/issues/791#issuecomment-877837906)

**Comment by MoaidHathot** [comment]
Hi @IbraWorks, thank you for pointing this out! I have documented the dependency.
I will try to auto-recognize the OS being used in order to automatically use "fdfind" instead of "fd" on Debian based distros.

**Comment by MoaidHathot** [comment]
@IbraWorks, I removed the dependency on 'fd' completely. I now use native-lua libraries which are also faster.
Thank you for noticing and creating this issue :)
