### ISSUE TITLE
Configure telescope to show file names

### ISSUE THREAD

**Issue by marcinjahn** [MoaidHathot/dotnet.nvim#5]
When paths are long, the telescope explorer is a bit difficult to navigate

![image](https://github.com/user-attachments/assets/36ff441f-da91-4c42-8367-8a019aba31d9)

**Comment by MoaidHathot** [comment]
@marcinjahn, good point, thank you for pointing this out.
I'm wondering what would be the best approach. I can show only the file names but I think paths can be helpful too.
I'll try a few things, but will love to hear more ideas.

**Comment by MoaidHathot** [comment]
@marcinjahn, I added support for Telescope's `path_display` option. Basically, you can use any option that Telescope [supports](https://github.com/nvim-telescope/telescope.nvim/blob/5972437de807c3bc101565175da66a1aa4f8707a/doc/telescope.txt#L269). 
The default in `dotnet.nvim` now is `filename_first` which looks like that:

![image](https://github.com/user-attachments/assets/61d20bf5-9fe5-43f4-a446-48e11597ef23)

**Comment by marcinjahn** [comment]
Awesome, thanks
